language: node_js
node_js:
    - "0.10"
    - "iojs-v1.1.0"

before_install:
    - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
    - sudo dpkg -i influxdb_latest_amd64.deb
    - sudo /etc/init.d/influxdb start
